### Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name" : "Ainun",
  "email" : "ain@gmail.com",
  "password" : "ainun123",
  "password_confirmation": "ainun123"
}

### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "ain@gmail.com",
  "password": "ainun123"
}

### Logout
POST http://localhost:8000/api/logout
Authorization : Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzU0MjYyMzMzLCJleHAiOjE3NTQyNjU5MzMsIm5iZiI6MTc1NDI2MjMzMywianRpIjoibWx1dEQ1UTRSTk42N1JCdyIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.rC00-2lUn9GEJvcusOg3ClrDeL4jzkP43FuPdShy2Jw

### Get User Details
GET http://localhost:8000/api/user/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzU0MjgxNTE0LCJleHAiOjE3NTQyODUxMTQsIm5iZiI6MTc1NDI4MTUxNCwianRpIjoiTDZQNnhFVWpwSnNhN1dweSIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.7gAXOC2RckEcQQYVeECCDiandhcCVduCEs1OofAeRcA

### Update User Details
PUT http://localhost:8000/api/user/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzU0MjgwODEzLCJleHAiOjE3NTQyODQ0MTMsIm5iZiI6MTc1NDI4MDgxMywianRpIjoiY1YyY0ZFMlBtaVAzWHV0RyIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.nL3U5C3PVci0VlOI1PA3cbXuArk5DnUipmU-VnBk3Ho

{
  "name": "Najib",
  "email": "ain@gmail.com"
}