### Get Articles
GET http://localhost:8000/api/articles
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzU0MjgxNTE0LCJleHAiOjE3NTQyODUxMTQsIm5iZiI6MTc1NDI4MTUxNCwianRpIjoiTDZQNnhFVWpwSnNhN1dweSIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.7gAXOC2RckEcQQYVeECCDiandhcCVduCEs1OofAeRcA
Content-Type: application/json

### Create Article
POST http://localhost:8000/api/articles
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzU0MjgxNTE0LCJleHAiOjE3NTQyODUxMTQsIm5iZiI6MTc1NDI4MTUxNCwianRpIjoiTDZQNnhFVWpwSnNhN1dweSIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.7gAXOC2RckEcQQYVeECCDiandhcCVduCEs1OofAeRcA

{
  "title": "My First Article",
  "content": "This is the content of my first article.",
  "author_id": 1
} 

### Get Article by ID
GET http://localhost:8000/api/articles/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzU0MjgxNTE0LCJleHAiOjE3NTQyODUxMTQsIm5iZiI6MTc1NDI4MTUxNCwianRpIjoiTDZQNnhFVWpwSnNhN1dweSIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.7gAXOC2RckEcQQYVeECCDiandhcCVduCEs1OofAeRcA

### Update Article
PUT http://localhost:8000/api/articles/3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzU0MjgxNTE0LCJleHAiOjE3NTQyODUxMTQsIm5iZiI6MTc1NDI4MTUxNCwianRpIjoiTDZQNnhFVWpwSnNhN1dweSIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.7gAXOC2RckEcQQYVeECCDiandhcCVduCEs1OofAeRcA

{
  "title": "Updated Article Title",
  "content": "This is the updated content of the article."
}

### Delete Article
DELETE http://localhost:8000/api/articles/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzU0MjgxNTE0LCJleHAiOjE3NTQyODUxMTQsIm5iZiI6MTc1NDI4MTUxNCwianRpIjoiTDZQNnhFVWpwSnNhN1dweSIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.7gAXOC2RckEcQQYVeECCDiandhcCVduCEs1OofAeRcA

### Get User Articles
GET http://localhost:8000/api/my-articles
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzU0MjgxNTE0LCJleHAiOjE3NTQyODUxMTQsIm5iZiI6MTc1NDI4MTUxNCwianRpIjoiTDZQNnhFVWpwSnNhN1dweSIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.7gAXOC2RckEcQQYVeECCDiandhcCVduCEs1OofAeRcA